PRAGMA foreign_keys = ON;
BEGIN;

INSERT OR IGNORE INTO routes (route_code, name, description) VALUES
('BLEKINGE', 'Blekingerundan', 'Blekingerundan version 1: verifierad adressbaserad tisdagsrunda i Kristianstad, Bromölla, Sölvesborg, Asarum och Karlshamn. Stoppordningen är en första geografisk arbetsordning och är ännu inte fullständigt tidsoptimerad.');

INSERT OR IGNORE INTO shops (
    public_id, route_code, name, address, postcode, locality,
    latitude, longitude, tuesday_opens, tuesday_closes, tuesday_status,
    source_url, source_type, checked_at, assessment, candidate_status,
    stop_order, visit_minutes, notes
) VALUES
('blekinge-butiken-bromolla', 'BLEKINGE', 'Butiken Secondhand Bromölla', 'Industrigatan 3', NULL, 'Bromölla', NULL, NULL, '09:30', '12:00', 'verified_open', 'https://www.bromolla.se/butiken', 'official_website', '2026-07-26', 'Villkorat kommunalt återbruksstopp med kläder, textilier och mindre prylar; kort tisdagsfönster och svagare profil för möbler och större elektronik.', 'conditional', 1, 30, 'Adress och tisdagstid verifierade på Bromölla kommuns sida. Postnummer och koordinater lämnas NULL. Stoppordningen är inte fullständigt tidsoptimerad.'),
('blekinge-majas-kristianstad', 'BLEKINGE', 'Majas Secondhand Kristianstad', 'Nässelvägen 5', '291 59', 'Kristianstad', NULL, NULL, '10:00', '18:00', 'verified_open', 'https://www.majassecondhand.se/om-oss/', 'official_website', '2026-07-26', 'Hög prioritet: cirka 1100 kvadratmeter och bred second hand-profil med tydligt fyndvärde.', 'selected', 2, 60, 'Adress, postnummer, butiksstorlek och tisdagstid verifierade på verksamhetens officiella webbplats. Koordinater lämnas NULL.'),
('blekinge-roda-korset-kristianstad', 'BLEKINGE', 'Röda Korset Second hand Kristianstad', 'Östra Vallgatan 19', '291 31', 'Kristianstad', NULL, NULL, '10:00', '16:00', 'verified_open', 'https://www.rodakorset.se/ort/skane/kristianstads-kommun/second-hand/roda-korset-second-hand-kristianstad/', 'official_website', '2026-07-26', 'Normal prioritet: centralt och stabilt välgörenhetsstopp.', 'selected', 3, 35, 'Adress, postnummer och tisdagstid verifierade på Röda Korsets officiella butikssida. Koordinater lämnas NULL.'),
('blekinge-pmu-kristianstad', 'BLEKINGE', 'PMU Second Hand Kristianstad', 'Näsbychaussén 119', '291 36', 'Kristianstad', NULL, NULL, '12:00', '17:00', 'verified_open', 'https://pmu.se/butik/kristianstad/', 'official_website', '2026-07-26', 'Hög prioritet: möbler, teknik, böcker, husgeråd, fritidsprylar och kafé.', 'selected', 4, 60, 'Adress, postnummer, sortiment och tisdagstid verifierade på PMU:s officiella butikssida. Koordinater lämnas NULL.'),
('blekinge-erikshjalpen-kristianstad', 'BLEKINGE', 'Erikshjälpen Second Hand Kristianstad', 'Karlsgatan 47', '291 59', 'Kristianstad', NULL, NULL, '12:00', '18:00', 'verified_open', 'https://erikshjalpen.se/butiker/second-hand-kristianstad/', 'official_website', '2026-07-26', 'Hög prioritet: över 1500 kvadratmeter med möbler och brett sortiment.', 'selected', 5, 60, 'Adress, postnummer, butiksstorlek, sortiment och tisdagstid verifierade på Erikshjälpens officiella butikssida. Koordinater lämnas NULL.'),
('blekinge-tva-hjartan-solvesborg', 'BLEKINGE', 'Två Hjärtan Sölvesborg', 'Skånevägen 32', NULL, 'Sölvesborg', NULL, NULL, '10:00', '18:00', 'verified_open', 'https://tvahjartan.com/', 'official_website', '2026-07-26', 'Normal prioritet: ideell second hand med bred vardagsöppettid.', 'selected', 6, 45, 'Adress och tisdagstid verifierade på verksamhetens officiella webbplats. Postnummer och koordinater lämnas NULL.'),
('blekinge-norreboden-solvesborg', 'BLEKINGE', 'Norreboden Second Hand', 'Norra Bryggerigatan 3', '294 34', 'Sölvesborg', NULL, NULL, '16:00', '19:00', 'verified_open', 'https://www.folkkyrkan.se/kontakt', 'official_website', '2026-07-26', 'Villkorat stopp med möbler, kläder, leksaker och prylar; öppnar sent på tisdagen.', 'conditional', 7, 45, 'Adress, postnummer, sortiment och tisdagstid verifierade på verksamhetens officiella webbplats. Koordinater lämnas NULL. Sen öppning kräver särskild tidsplanering.'),
('blekinge-varuformedling-asarum', 'BLEKINGE', 'Blekinge Varuförmedling', 'Verkstadsvägen 1', '374 50', 'Asarum', NULL, NULL, '12:00', '18:00', 'verified_open', 'https://blekingevaruformedling.se/kontakt/', 'official_website', '2026-07-26', 'Hög prioritet: stark loppisprofil med verktyg, elektronik, vinyl, möbler och hushållsvaror.', 'selected', 8, 60, 'Adress, postnummer, sortiment och tisdagstid verifierade på verksamhetens officiella webbplats. Koordinater lämnas NULL.'),
('blekinge-hallbaren-karlshamn', 'BLEKINGE', 'Hållbaren Karlshamn', 'Boktryckargatan 3', NULL, 'Karlshamn', NULL, NULL, '10:00', '15:30', 'verified_open', 'https://www.karlshamn.se/bygga-bo-och-miljo/avfall-och-atervinning/hallbaren/', 'official_website', '2026-07-26', 'Villkorat kommunalt återbruksstopp med kortare dag och lunchstängning.', 'conditional', 9, 35, 'Adress och vardagstid verifierade på Karlshamns kommuns sida. Sidan anger lunchstängt 12:00–13:00; exporten använder ytterintervallet 10:00–15:30. Postnummer och koordinater lämnas NULL.'),
('blekinge-34ans-fynd-karlshamn', 'BLEKINGE', '34:ans Fynd Karlshamn', 'Rörvägen 4', '374 32', 'Karlshamn', NULL, NULL, '13:00', '18:00', 'verified_open', 'https://www.34ansfynd.se/', 'official_website', '2026-07-26', 'Hög prioritet: större second hand-butik med kafé och bred fyndprofil.', 'selected', 10, 60, 'Adress, postnummer och tisdagstid verifierade på verksamhetens officiella webbplats. Koordinater lämnas NULL.'),
('blekinge-roda-korset-karlshamn', 'BLEKINGE', 'Röda Korset Second hand Karlshamn', 'Strömmavägen 2', '374 32', 'Karlshamn', NULL, NULL, '13:00', '17:00', 'verified_open', 'https://www.rodakorset.se/ort/blekinge/karlshamns-kommun/second-hand/roda-korset-second-hand-karlshamn/', 'official_website', '2026-07-26', 'Normal prioritet: cirka 700 kvadratmeter med mindre möbler, media, elektronik och husgeråd.', 'selected', 11, 45, 'Adress, postnummer, butiksstorlek, sortiment och tisdagstid verifierade på Röda Korsets officiella butikssida. Koordinater lämnas NULL.');

COMMIT;
